
spring:
  datasource:
    url: jdbc:h2:mem:orders-db
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false
